# path_planner parameters for DONKEYBOTI caterpillar robot
# A* global planner + Pure Pursuit + DWA local planner
#
# [v9] Inflation removed — now handled by terrain_costmap v3
#      A* reads pre-inflated costmap directly
#      DWA also benefits from inflated costs (no longer blind to wall proximity)

path_planner_node:
  ros__parameters:
    # --- Costmap (must match terrain_costmap) ---
    costmap_size: 5.0
    costmap_resolution: 0.1

    # --- Robot kinematics ---
    max_lin_vel: 0.6
    min_lin_vel: -0.2
    max_ang_vel: 0.5
    max_lin_acc: 1.0
    max_ang_acc: 2.0

    # --- DWA sampling ---
<<<<<<< HEAD
    n_v_samples: 11
    n_w_samples: 21
    sim_time: 2.0               # longer horizon for smoother paths
    sim_granularity: 0.1

    # --- DWA scoring weights ---
    weight_heading: 0.5
    weight_clearance: 1.2       # high — obstacle avoidance priority
    weight_velocity: 0.6
    weight_path_dist: 0.6
=======
    n_v_samples: 11             # linear velocity samples
    n_w_samples: 21             # angular velocity samples
    sim_time: 2.0               # [s] forward simulation horizon
    sim_granularity: 0.1        # [s] simulation time step

    # --- DWA scoring weights ---
    # [v3] Rebalanced: velocity↑, heading↓ to prevent unnecessary spinning
    # weight_heading: 1.0       # [v1-v2]
    weight_heading: 0.5         # [v3] heading alignment (reduced)
    weight_clearance: 1.2       # terrain cost / obstacle distance
    # weight_velocity: 0.3      # [v1-v2]
    weight_velocity: 0.6        # [v3] forward motion preference (increased)
    weight_path_dist: 0.6       # closeness to A* global path
>>>>>>> 2ecc61b68229f864b9acf00d65dfb9dbdfe7b6bc

    # --- Goal tolerance ---
    goal_xy_tolerance: 0.3

    # --- A* configuration ---
    astar_lethal_cost: 90.0
    astar_cost_weight: 3.0      # inflated costs already high, this amplifies further

    # --- Robot footprint ---
    robot_length: 1.432
    robot_width: 0.850
    clearance_margin: 0.1

    # --- [v9] Inflation disabled in path_planner ---
    # Set to 0 — costmap already inflated by terrain_costmap v3
    inflation_radius: 0.0

    # --- Control ---
    control_rate: 20.0

    # --- Frames ---
    odom_frame: "odom"
    robot_frame: "base_link"

    # --- Topics ---
    costmap_topic: "/terrain_costmap"
    goal_topic: "/goal_pose"
    cmd_vel_topic: "/cmd_vel"

    # --- Slope ---
    slope_speed_factor: 0.5
    slope_threshold_deg: 15.0

    # --- Path Caching & Pure Pursuit ---
<<<<<<< HEAD
    replan_interval: 2.0
    path_deviation_threshold: 0.5
    pure_pursuit_lookahead: 0.8
    pure_pursuit_lookahead_min: 0.4
    pure_pursuit_lookahead_max: 1.2
    velocity_lookahead_gain: 0.5
=======
    replan_interval: 2.0              # [s] periodic A* replan interval
    path_deviation_threshold: 0.5     # [m] replan if robot deviates this far
    pure_pursuit_lookahead: 0.6       # [m] base lookahead distance
    pure_pursuit_lookahead_min: 0.4   # [m] minimum lookahead (low speed)
    pure_pursuit_lookahead_max: 1.2   # [m] maximum lookahead (high speed)
    velocity_lookahead_gain: 0.5      # lookahead = base + gain * |v|
>>>>>>> 2ecc61b68229f864b9acf00d65dfb9dbdfe7b6bc

    # --- Spin prevention ---
    spin_heading_threshold: 1.05

    # --- Recovery ---
    recovery_enabled: true
    recovery_fail_count: 5
    recovery_reverse_vel: -0.15
    recovery_reverse_duration: 1.5
    recovery_max_attempts: 3