# GroundGrid config for Pacecat LDS-M300-E LiDAR
# Non-repetitive scanning, 200kHz, ~20K pts/frame @10Hz
# Based on helipr_avia.yaml (also non-repetitive)
# Tuned for mountain terrain
groundgrid_node:
  ros__parameters:
    groundgrid/dataset_name: "live"
    groundgrid/sensor: "Avia"
    groundgrid/point_count_cell_variance_thres: 10
    groundgrid/max_ring: 1024
    groundgrid/groundpatch_detection_minimum_thres: 0.01
    groundgrid/distance_factor: 0.001
    groundgrid/min_distance_factor: 0.0005
    groundgrid/min_point_height_thres: 0.4
    groundgrid/min_point_height_obstacle_thres: 0.15
    groundgrid/outlier_tolerance: 0.15
    groundgrid/min_ground_patch_detection_point_count_thres: 0.125
    groundgrid/patch_size_change_distance: 15.0
    groundgrid/occupied_cells_decrease_factor: 10.0
    groundgrid/occupied_cells_point_count_factor: 20.0
    groundgrid/min_outlier_detection_ground_confidence: 0.5
    groundgrid/max_threads: 4
    groundgrid/horizontal_point_ang_dist: 0.0031
    groundgrid/min_dist_squared: 0.25